# Generated by Django 4.2 on 2025-01-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='catch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='middle_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
